import os

def new():
    fname = raw_input("FIRST NAME: ")
    fname = str(fname)
    lname = raw_input("LAST NAME: ")
    lname = str(lname)
    phone = raw_input("PHONE (xxxxxxxxxx): ")
    phone = str(phone)
    email = raw_input("EMAIL: ")
    email = str(email)
    city = raw_input("CITY: ")
    city = str(city)
    state = raw_input("STATE: ")
    state = str(state)
    jobtitle = raw_input("JOB TITLE: ")
    jobtitle = str(jobtitle)
    newcard = open(fname + "_" + lname + ".vcf","w")
    newcard.write('BEGIN:VCARD\n')
    newcard.write('VERSION:2.1\n')
    newcard.write('JOB:' + jobtitle + '\n')
    newcard.write('N:;' + fname + '\n')
    newcard.write('FN:' + lname + ',' + fname + '\n')
    newcard.write('TEL;WORK;VOICE:' + phone + '\n')
    newcard.write('EMAIL:' + email + '\n')
    newcard.write('CITY:' + city + '\n')
    newcard.write('STATE:' + state + '\n')
    newcard.write('END:VCARD\n')
    newcard.close()
    os.system("mv " + fname + "_" + lname + ".vcf ~/Desktop/" + fname + "_" + lname + ".vcf")
